apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: tap-workshop-templates
  description: A collection of RHDH templates for the Trusted Application Pipeline workshop.
spec:
  type: url
  targets:
     - https://{{ gitlab_host }}/{{ gitlab_group }}/tap-workshop-templates/blob/main/scaffolder-templates/quarkus-secure-template/template.yaml
     - https://{{ gitlab_host }}/{{ gitlab_group }}/tap-workshop-templates/blob/main/scaffolder-templates/quarkus-insecure-template/template.yaml
